batch_size: 32
total_steps: 300000
cls_reg_every: 2  # how often to apply classification regularization
orth_reg: 100.0

log_every: 100
save_every: 5000
sample_every: 500
n_workers: 8
lr: 1e-4
fid: False

fine_tune_from: /home/kinakh/Development/Projects/eigen-ae/logs/afhq/20210804_215558_cls_2_classes_3/checkpoints/0200000.pt

loss: hinge

dataset:
  name: afhq
  path: /home/kinakh/Datasets/animal_faces/afhq/train
  size: 256
  n_out: 3
  n_channels: 3

encoder:
  path: ./models/AFHQ/afhq.pth
  base_model: resnet50
  out_dim: 128

classifier:
  path: ./models/AFHQ/afhq_classifier_3.pth
  n_features: 2048

generator:
  z_size: 512
  n_basis: 6
  noise_size: 512

discriminator_eps:
  inner_dim: 1024
  input_dim: 2048

comment: afhq_generation_only_epsilon
