batch_size: 256  # batch size to use, when training classifier
epochs: 200      # number of training epochs

wd: 1e-6  # weight decay
lr: 3e-4  # learning rate

fine_tune_from:  # path to model, to fine tune from

model:              # classification model parameters
  n_features: 2048  # number of input features
  n_out: <>         # number of classes

dataset:                                   # dataset parameters
  name: afhq                               # dataset name
  train_path: <path to train images>       # path to folder with train images
  train_anno: <path to train annotations>  # path to csv file with train annotations, remove if you want to use ImageFolder dataset
  test_path: <path to test images>         # path to folder with test images
  test_anno: <path to test annotations>    # path to csv file with test annotations, remove if you want to use ImageFolder dataset
  size: 256                                # image size

encoder:                        # SimCLR encoder parameters
  path: ./models/AFHQ/afhq.pth  # path to pretrained encoder model
  base_model: resnet50          # encoder base model
  n_channels: 3                 # number of image channels
  out_dim: 128                  # z-projection size

comment: afhq_classification  # name of the experiment, will be used for checkpoint folder