batch_size: 128
total_steps: 200000
cls_reg_every: 8  # how often to apply classification regularization
d_reg_every: 16   # how often to apply d regularization
d_reg: 10.0
orth_reg: 100.0

log_every: 100
save_every: 5000
sample_every: 500
n_workers: 8
lr: 1e-4

fine_tune_from: /home/kinakh/Development/Projects/eigen-ae/logs/celeba/20210901_143135/checkpoints/0095000.pt

loss: hinge

dataset:
  name: celeba
  path: /home/kinakh/Datasets/CelebA/Img/img_align_celeba
  anno: /home/kinakh/Datasets/CelebA/Anno/list_attr_celeba.txt
  size: 128
  n_out: 40
  n_channels: 3

encoder:
  path: ./models/CelebA/celeba.pth
  base_model: resnet50
  out_dim: 128

classifier:
  path: ./models/CelebA/celeba_classifier.pth
  n_features: 2048

generator:
  z_size: 512
  n_basis: 6
  noise_size: 512

discriminator:
  type: oneclass

comment: celeba_generation