batch_size: 64
total_steps: 200000
cls_reg_every: 2  # how often to apply classification regularization
d_reg_every: 16   # how often to apply d regularization
d_reg: 10.0
orth_reg: 100.0

log_every: 100
save_every: 5000
sample_every: 500
n_workers: 8
lr: 1e-4
fid: False

fine_tune_from: ./runs/CelebA/Sep16_18-36-56_wyner_celeba_generation_sel_columns_15_500k/checkpoint/0500000.pt

loss: hinge

dataset:
  name: celeba
  path: /home/kinakh/Datasets/CelebA/Img/img_align_celeba
  anno: /home/kinakh/Datasets/CelebA/Anno/list_attr_celeba.txt
  columns: ['Bald', 'Blurry', 'Chubby', 'Double_Chin', 'Eyeglasses', 'Goatee', 'Gray_Hair', 'Mustache', 'Narrow_Eyes', 'Pale_Skin', 'Receding_Hairline', 'Rosy_Cheeks', 'Sideburns', 'Wearing_Hat', 'Wearing_Necktie']
  size: 128
  n_out: 15
  n_channels: 3

encoder:
  path: ./models/CelebA/celeba.pth
  base_model: resnet50
  out_dim: 128

classifier:
  path: ./models/CelebA/celeba_classifier_sel_columns_15.pth
  n_features: 2048

generator:
  z_size: 512
  n_basis: 6
  noise_size: 512
  y_type: real   # can be `one_hot`, `multi_label`, `mixed`, `real`

discriminator:
  type: oneclass

comment: celeba_generation_sel_columns_15_eval