batch_size: 64        # batch size to use, when training generator
total_steps: 200000   # number of total training steps
cls_reg_every: 2      # how often to apply classification regularization
d_reg_every: 16       # how often to apply d regularization
d_reg: 10.0           # d regularization parameter
orth_reg: 100.0       # generator orthogonal regularization parameter

log_every: 100     # how often to log losses to tensorboard
save_every: 5000   # how often to save model checkpoints
sample_every: 500  # how often to save generated images
n_workers: 8       # number of workers in dataloader
lr: 1e-4           # learning rate
fid: False         # if True, then FID will be calculated when saving checkpoint model

fine_tune_from:  # path to model, to fine tune from

loss: hinge  # type of loss to use. Options: 'hinge', 'non_saturating' and 'lsgan'

dataset:                       # dataset parameters
  name: celeba                 # dataset name
  path: <path to images>       # path to folder with images
  anno: <path to annotations>  # path to file with attribute annotations
  size: 128                    # image size
  n_out: <>                    # number of attributes for each image
  n_channels: 3                # number of channels in image

encoder:                # encoder parameters
  path:  <>             # path to pretrained encoder model
  base_model: resnet50  # encoder base model
  out_dim: 128          # z-projection size

classifier:         # classifier parameters
  path: <>          # path to pretrained classifier model
  n_features: 2048  # number of input features in the classifier model

generator:             # generator parameters
  z_size: 512          # z vector size
  n_basis: 6           # size of the z1, ... zk input variables
  noise_size: 512      # size of the generator input (generator input is attributes mixed with z vector sampled from N(0, 1))
  y_type: multi_label  # type of attributes. Choices: 'one_hot' and 'multi_label'

discriminator:    # discriminator parameters
  type: oneclass  # type of discriminator. Choices: 'oneclass' and 'patch'

comment: celeba_generation