batch_size: 512
epochs: 1

wd: 1e-6
lr: 3e-4

fine_tune_from: ./models/FashionMNIST/fashionmnist_classifier.pth

model:
  n_features: 512
  n_out: 10

dataset:
  name: fashionmnist
  size: 32

encoder:
  path: ./models/FashionMNIST/fashionmnist.pth
  base_model: resnet18
  n_channels: 1
  out_dim: 256

comment: fashionmnist_classification