batch_size: 32
total_steps: 300000
cls_reg_every: 2  # how often to apply classification regularization
d_reg_every: 16   # how often to apply d regularization
d_reg: 10.0
orth_reg: 100.0

log_every: 100
save_every: 5000
sample_every: 500
n_workers: 12
lr: 1e-4
fid: False

fine_tune_from: ./runs/Sep17_22-53-39_nv02_ffhq_generation_cls_2/checkpoint/0200000.pt

loss: hinge

dataset:
  name: ffhq
  path: /home/kinakh/Datasets/FFHQ/imgs
  anno: /home/kinakh/Datasets/FFHQ/ffhq_aging_labels.csv
  size: 128
  n_out: 12
  n_channels: 3

encoder:
  path: ./models/FFHQ/FFHQ.pth
  base_model: resnet50
  out_dim: 128

classifier:
  path: ./models/FFHQ/FFHQ_classifier.pth
  n_features: 2048

generator:
  z_size: 512
  n_basis: 6
  noise_size: 512
  y_type: real

discriminator:
  type: oneclass

comment: ffhq_generation_cls_2