batch_size: 64
epochs: 200

wd: 1e-6
lr: 3e-4

fine_tune_from:

model:
  n_features: 2048
  n_out: 12

dataset:
  name: ffhq
  path: /home/kinakh/Datasets/FFHQ/imgs
  anno: /home/kinakh/Datasets/FFHQ/ffhq_aging_labels.csv
  size: 256

encoder:
  path: ./models/FFHQ/FFHQ.pth
  base_model: resnet50
  n_channels: 3
  out_dim: 128

comment: ffhq_classification